from __future__ import annotations

from datetime import date


DISCLAIMER = (
    "This report is for learning and informational use only. "
    "It is not investment advice."
)


def build_markdown_report(
    funds: list[dict[str, object]],
    report_date: date,
    history_comparison: dict[str, object] | None = None,
) -> str:
    lines = [
        f"# Fund Daily Report - {report_date.isoformat()}",
        "",
        f"> {DISCLAIMER}",
        "",
    ]
    lines.extend(build_overview_section(funds=funds, history_comparison=history_comparison))
    lines.extend(build_history_section(history_comparison=history_comparison))
    lines.extend(build_fund_sections(funds=funds, report_date=report_date))
    lines.extend(build_footer_section())
    return "\n".join(lines)


def build_overview_section(
    funds: list[dict[str, object]],
    history_comparison: dict[str, object] | None,
) -> list[str]:
    fund_count = len(funds)
    high_risk_count = sum(1 for fund in funds if fund.get("risk_level") == "high")
    medium_risk_count = sum(1 for fund in funds if fund.get("risk_level") == "medium")
    has_history = bool(history_comparison and history_comparison.get("has_previous_report"))

    return [
        "## Daily Summary",
        f"- Funds covered: {fund_count}",
        f"- Medium risk signals: {medium_risk_count}",
        f"- High risk signals: {high_risk_count}",
        f"- History comparison: {'available' if has_history else 'not available'}",
        "",
    ]


def build_history_section(history_comparison: dict[str, object] | None) -> list[str]:
    summary = (
        str(history_comparison.get("summary"))
        if history_comparison
        else "No comparison available."
    )
    return [
        "## History Comparison",
        f"- {summary}",
        "",
    ]


def build_fund_sections(funds: list[dict[str, object]], report_date: date) -> list[str]:
    if not funds:
        return [
            "## Fund Details",
            "- No matching fund data found.",
            "",
        ]

    lines = ["## Fund Details", ""]
    for fund in funds:
        lines.extend(build_single_fund_section(fund=fund, report_date=report_date))
    return lines


def build_single_fund_section(fund: dict[str, object], report_date: date) -> list[str]:
    name = str(fund["fund_name"])
    code = str(fund["fund_code"])
    nav = str(fund["nav"])
    change = float(str(fund["daily_change_percent"]))
    theme = str(fund["theme"])
    nav_date = str(fund.get("nav_date", report_date.isoformat()))
    risk_level = str(fund.get("risk_level", "unknown"))
    seven_day_return = format_optional_percent(fund.get("seven_day_return_percent"))
    thirty_day_return = format_optional_percent(fund.get("thirty_day_return_percent"))
    max_daily_change_7d = format_optional_percent(fund.get("max_daily_change_7d"))
    trend_7d = str(fund.get("trend_7d", "unknown"))
    drawdown_30d = format_optional_percent(fund.get("drawdown_30d"))
    change_summary = str(fund.get("change_summary", "No change summary available."))
    snapshot_summary = get_snapshot_summary(fund)
    direction = "rose" if change >= 0 else "fell"

    return [
        f"### {name} ({code})",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Theme | {theme} |",
        f"| Latest NAV | {nav} |",
        f"| NAV Date | {nav_date} |",
        f"| Daily Change | {change:.2f}% |",
        f"| 7D Return | {seven_day_return} |",
        f"| 30D Return | {thirty_day_return} |",
        f"| Max Daily Change 7D | {max_daily_change_7d} |",
        f"| Trend 7D | {trend_7d} |",
        f"| Drawdown 30D | {drawdown_30d} |",
        f"| Risk Level | {risk_level} |",
        "",
        f"- Change Summary: {change_summary}",
        f"- Snapshot Comparison: {snapshot_summary}",
        (
            f"- Basic View: {name} {direction} {abs(change):.2f}% today. "
            "Review the NAV date, risk level, and snapshot comparison before drawing conclusions."
        ),
        "",
    ]


def get_snapshot_summary(fund: dict[str, object]) -> str:
    snapshot_comparison = fund.get("snapshot_comparison", {})
    if isinstance(snapshot_comparison, dict):
        return str(snapshot_comparison.get("summary", "No snapshot comparison available."))
    return "No snapshot comparison available."


def format_optional_percent(value: object) -> str:
    if value is None:
        return "unknown"
    try:
        return f"{float(str(value)):.2f}%"
    except (TypeError, ValueError):
        return "unknown"


def build_footer_section() -> list[str]:
    return [
        "## Notes",
        "- Risk level is generated by a simple rule based on daily percentage change.",
        "- Snapshot comparison uses previously stored local fund snapshots.",
        f"- Disclaimer: {DISCLAIMER}",
        "",
    ]


def build_llm_template_instruction() -> str:
    return """
Use this markdown structure exactly:

# Fund Daily Report - <date>

> <learning and informational disclaimer>

## Daily Summary
- Funds covered: <count>
- Key observation: <one short sentence>
- Main risk signal: <one short sentence>

## History Comparison
- <brief comparison with previous run>

## Fund Details

### <fund name> (<fund code>)
| Field | Value |
| --- | --- |
| Theme | <theme> |
| Latest NAV | <nav> |
| NAV Date | <nav date> |
| Daily Change | <daily change> |
| 7D Return | <seven day return> |
| 30D Return | <thirty day return> |
| Max Daily Change 7D | <max daily change in 7 days> |
| Trend 7D | <up/down/mixed> |
| Drawdown 30D | <30 day drawdown> |
| Risk Level | <risk level> |

- Change Summary: <short explanation>
- Snapshot Comparison: <comparison with previous local snapshot>
- Analysis: <short beginner-friendly interpretation>

## Notes
- Explain that risk level is rule-based, not a professional risk rating.
- State that the report is for learning and informational use only.
""".strip()
